minetest.register_alias("0", "air")
minetest.register_alias("1", "default:stone")
minetest.register_alias("2", "default:dirt_with_grass")
minetest.register_alias("3", "default:dirt")
minetest.register_alias("4", "default:cobble")
minetest.register_alias("5", "default:wood")
minetest.register_alias("5:1", "default:stone")
minetest.register_alias("5:2", "default:aspen_wood")
minetest.register_alias("5:3", "default:junglewood")
minetest.register_alias("5:4", "default:acacia_wood")
minetest.register_alias("5:5", "default:stone")

minetest.register_alias("6", "default:sapling")
minetest.register_alias("6:1", "default:sapling")
minetest.register_alias("6:2", "default:aspen_sapling")
minetest.register_alias("6:3", "default:junglesapling")
minetest.register_alias("6:4", "default:acacia_sapling")
minetest.register_alias("6:5", "default:sapling")

minetest.register_alias("7", "default:stone")
minetest.register_alias("8", "default:water_flowing")
minetest.register_alias("9", "default:water_source")
minetest.register_alias("10", "default:lava_flowing")
minetest.register_alias("11", "default:lava_source")
minetest.register_alias("12", "default:sand")
minetest.register_alias("12:1", "default:silver_sand")
minetest.register_alias("13", "default:gravel")
minetest.register_alias("14", "default:stone_with_gold")
minetest.register_alias("15", "default:stone_with_iron")
minetest.register_alias("16", "default:stone_with_coal")

minetest.register_alias("17", "default:tree")
minetest.register_alias("17:1", "default:tree")
minetest.register_alias("17:2", "default:aspen_tree")
minetest.register_alias("17:3", "default:jungletree")
minetest.register_alias("17:4", "default:acacia_tree")



